app:
  port: ${APP_PORT}
  host: ${APP_HOST}
  domain: ${APP_DOMAIN}
  development: ${APP_DEVELOPMENT}
  secret: ${APP_SECRET}
  unsplash: ${APP_UNSPLASH}

db:
  database: ${DB_DATABASE}

service:
  user: ${SERVICE_USER}
  profile: ${SERVICE_PROFILE}
