app:
  port: ${APP_PORT}
  domain: ${APP_DOMAIN}
  development: ${APP_DEVELOPMENT}
  secret: ${APP_SECRET}

db:
  database: ${DB_DATABASE}

service:
  user: ${SERVICE_USER}
  profile: ${SERVICE_PROFILE}
  unsplash: ${SERVICE_UNSPLASH}
  google:
    id: ${SERVICE_GOOGLE_ID}
    secret: ${SERVICE_GOOGLE_SECRET}
    redirect: ${SERVICE_GOOGLE_REDIRECT}
